src/WebUI/SurveyApp.Mvc/Controllers/SurveysController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Azure.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using SurveyApp.DataTransferObjects.Requests;
using SurveyApp.DataTransferObjects.Responses;
using SurveyApp.Mvc.CacheTools;
using SurveyApp.Mvc.Models;
using SurveyApp.Services.Services;
using System.Diagnostics;

namespace SurveyApp.Mvc.Controllers
{
    public class SurveysController : Controller
    {
        private readonly ILogger<SurveysController> _logger;
        private readonly ISurveyService _surveyService;
        private readonly ISurveyTypeService _surveyTypeService;
        private readonly IResponseService _responseService;
        private readonly IAnswerService _answerService;
        private readonly IAnswerOptionService _answerOptionService;
        private readonly ISurveyStatusService _surveyStatusService;
        private readonly IMemoryCache _memoryCache;
        private readonly INotyfService _notyf;
        public SurveysController(ILogger<SurveysController> logger, ISurveyService surveyService, IAnswerService answerService, IAnswerOptionService answerOptionService, IResponseService responseService, ISurveyStatusService surveyStatusService, ISurveyTypeService surveyTypeService, IMemoryCache memoryCache, INotyfService notyf)
        {
            _logger = logger;
            _surveyService = surveyService;
            _answerService = answerService;
            _answerOptionService = answerOptionService;
            _responseService = responseService;
            _surveyStatusService = surveyStatusService;
            _surveyTypeService = surveyTypeService;
            _memoryCache = memoryCache;
            _notyf = notyf;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> Display(int surveyId)
        {
            var survey = await _surveyService.GetByIdAsync(surveyId);
            return View(survey);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            ViewBag.SurveyStatus = await getSurveyStatusForSelectListAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SurveyRequest request)
        {
            if (ModelState.IsValid)
            {
                await _surveyService.CreateAsync(request);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.SurveyStatus = _surveyStatusService.GetAllAsync();
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.SurveyStatus = await getSurveyStatusForSelectListAsync();
            ViewBag.Surveys = await getSurveysForSelectListAsync();

            var survey = await _surveyService.GetByIdAsync(id);

            return View(survey);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, SurveyRequest request)
        {
            if (await _surveyService.SurveyIsExists(id))
            {
                if (ModelState.IsValid)
                {
                    await _surveyService.UpdateAsync(request);
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.SurveyStatus = getSurveyStatusForSelectListAsync();
                return View();
            }
            return NotFound();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete()
        {
            ViewBag.Surveys = await getSurveysForSelectListAsync();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (await _surveyService.SurveyIsExists(id))
            {
                if (ModelState.IsValid)
                {
                    await _surveyService.DeleteAsync(id);
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> SubmitAnswers(ResponseViewModel response)
        {

            try
            {
                var responseRequest = new SurveyResponseRequest
                {
                    RespondentId = 1,
                    SurveyId = response.SurveyId,
                };

                var responseId = await _responseService.CreateAndReturnIdAsync(responseRequest);

                foreach (var answer in response.Answers)
                {
                    var answerRequest = new AnswerRequest
                    {
                        AnswerText = answer.AnswerText,
                        QuestionId = answer.QuestionId,
                        ResponseId = responseId,
                    };

                    var answerId = await _answerService.CreateAndReturnIdAsync(answerRequest);

                    if (answer.AnswerOptionIds != null)
                    {
                        foreach (var answerOptionId in answer.AnswerOptionIds)
                        {
                            var answerOptionRequest = new AnswerOptionRequest
                            {
                                AnswerId = answerId,
                                QuestionOptionId = answerOptionId,
                            };
                            await _answerOptionService.CreateAsync(answerOptionRequest);
                        }
                    }

                    if (answer.AnswerOptionId != null)
                    {
                        var answerOptionRequest = new AnswerOptionRequest
                        {
                            AnswerId = answerId,
                            QuestionOptionId = answer.AnswerOptionId,
                        };
                        await _answerOptionService.CreateAsync(answerOptionRequest);
                    }

                }
                var successMessage = "Sending successful!";
                _notyf.Success(successMessage);
            }
            catch (Exception)
            {
                var errorMessage = "An error occurred, please try again.";
                _notyf.Error(errorMessage);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> GetSurveysByTypeId(int surveyTypeId)
        {
            var surveys = await _surveyService.GetSurveysByTypeIdAsync(surveyTypeId);
            return ViewComponent("SurveyList", surveys);
        }

        private async Task<IEnumerable<SelectListItem>> getSurveysForSelectListAsync()
        {
            var surveyList = await _surveyService.GetAllAsync();
            var selectListItems = surveyList.Select(survey => new SelectListItem
            {
                Value = survey.Id.ToString(),
                Text = survey.Name
            });
            return selectListItems;
        }

        private async Task<IEnumerable<SelectListItem>> getSurveyStatusForSelectListAsync()
        {
            var surveyStatusList = await _surveyStatusService.GetAllAsync();
            var selectListItems = surveyStatusList.Select(status => new SelectListItem
            {
                Value = status.Id.ToString(),
                Text = status.Status
            });
            return selectListItems;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/WebUI/SurveyApp.Mvc/ViewComponents/SurveysWithMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SurveyApp.Mvc.Models;
using SurveyApp.Services.Services;

namespace SurveyApp.Mvc.ViewComponents
{
    public class SurveysWithMenuViewComponent : ViewComponent
    {
        private readonly ISurveyService _surveyService;
        private readonly ISurveyTypeService _surveyTypeService;

        public SurveysWithMenuViewComponent(ISurveyService surveyService, ISurveyTypeService surveyTypeService)
        {
            _surveyService = surveyService;
            _surveyTypeService = surveyTypeService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var surveys = await _surveyService.GetAllAsync();
            var surveyTypes = await _surveyTypeService.GetAllAsync();

            var model = new SurveyComponentModel
            {
                Surveys = surveys,
                SurveyTypes = surveyTypes
            };

            return View(model);
        }
    }
}

src/WebUI/SurveyApp.Mvc/Views/Surveys/Create.cshtml
@model SurveyApp.DataTransferObjects.Requests.SurveyRequest

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SurveyRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinResponses" class="control-label"></label>
                <input asp-for="MinResponses" class="form-control" />
                <span asp-validation-for="MinResponses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxResponses" class="control-label"></label>
                <input asp-for="MaxResponses" class="form-control" />
                <span asp-validation-for="MaxResponses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SurveyStatusId" class="control-label"></label>
                <select asp-for="SurveyStatusId" class="form-control" asp-items="@ViewBag.SurveyStatus">
                    <option hidden="" value="disable selected">Anket durumu</option>
                </select>
                <span asp-validation-for="SurveyStatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/WebUI/SurveyApp.Mvc/Views/Surveys/Delete.cshtml
@model SurveyApp.DataTransferObjects.Requests.SurveyRequest

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SurveyRequest</h4>
    <hr />
    
    <form asp-action="Delete">
        <div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <select asp-for="Id" class="form-control" asp-items="@ViewBag.Surveys">
                <option hidden="" value="disable selected">Anket Seçiniz</option>
            </select>
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/WebUI/SurveyApp.Mvc/Views/Surveys/Display.cshtml
@model SurveyDisplayResponse

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 text-center">
        @using (Html.BeginForm("SubmitAnswers", "Surveys", FormMethod.Post))
        {
            <h2 class="mb-5">@Model.Name</h2>

            @for (int i = 0; i < Model.Questions.ToList().Count; i++)
            {
                var question = Model.Questions.ToList()[i];

                <h4>@question.QuestionText</h4>

                    @if (question.QuestionType.Type == "Single Elective")
                {
                    for (int j = 0; j < question.QuestionOptions.ToList().Count; j++)
                    {
                        var option = question.QuestionOptions.ElementAt(j);

                        <label>
                            @Html.RadioButton("Response.Answers[" + i + "].AnswerOptionId", option.Id) @option.Value
                            @Html.Hidden("Response.Answers[" + i + "].QuestionId", question.Id)
                        </label>
                        <br />
                    }
                }
                    else if (question.QuestionType.Type == "Multiple Choice")
                {
                    for (int j = 0; j < question.QuestionOptions.ToList().Count; j++)
                    {
                        var option = question.QuestionOptions.ElementAt(j);

                        <label>
                            @Html.CheckBox("Response.Answers[" + i + "].AnswerOptionIds", new { value = option.Id }) @option.Value
                            @Html.Hidden("Response.Answers[" + i + "].QuestionId", question.Id)
                        </label>
                        <br />
                    }
                }
                    else if (question.QuestionType.Type == "Single Line Of Plain Text")
                {
                    <label>
                        @Html.TextBox("Response.Answers[" + i + "].AnswerText")
                        @Html.Hidden("Response.Answers[" + i + "].QuestionId", question.Id)
                    </label>
                    <br />
                }
                else if (question.QuestionType.Type == "Evaluation")
                {
                    <label>
                        @Html.TextBox("Response.Answers[" + i + "].AnswerText", "", new { type = "range", value = "5", min = "" +question.QuestionOptions.FirstOrDefault().Value+ "", max = "" +question.QuestionOptions.LastOrDefault().Value+ "" })


                        @Html.Hidden("Response.Answers[" + i + "].QuestionId", question.Id)
                    </label>
                    <br />
                }
                <br />
            }

            @Html.Hidden("Response.SurveyId", Model.Id)
            <input type="submit" class="btn btn-primary" value="Anketi Gönder" />
        }
        </div>
    </div>
</div>

src/WebUI/SurveyApp.Mvc/Views/Surveys/Edit.cshtml
@model SurveyApp.DataTransferObjects.Requests.SurveyRequest

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SurveyRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <select asp-for="Id" class="form-control" asp-items="@ViewBag.Surveys">
                    <option hidden="" value="disable selected">Anket Seçiniz</option>
                </select>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinResponses" class="control-label"></label>
                <input asp-for="MinResponses" class="form-control" />
                <span asp-validation-for="MinResponses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxResponses" class="control-label"></label>
                <input asp-for="MaxResponses" class="form-control" />
                <span asp-validation-for="MaxResponses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SurveyStatusId" class="control-label"></label>
                <select asp-for="SurveyStatusId" class="form-control" asp-items="@ViewBag.SurveyStatus">
                    <option hidden="" value="disable selected">Anket durumu</option>
                </select>
                <span asp-validation-for="SurveyStatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/WebUI/SurveyApp.Mvc/Views/Surveys/Index.cshtml
<div class="page-margin">
    @await Component.InvokeAsync("SurveysWithMenu")
</div>