src/WebUI/SurveyApp.Mvc/Controllers/AnswersController.cs
using Microsoft.AspNetCore.Mvc;
using SurveyApp.Mvc.Models;
using SurveyApp.Services.Services;

namespace SurveyApp.Mvc.Controllers
{
    public class AnswersController : Controller
    {
        private readonly IResponseService _responseService;
        private readonly IAnswerService _answerService;
        private readonly IQuestionService _questionService;
        private readonly IAnswerOptionService _answerOptionService;
        public AnswersController(IResponseService responseService, IAnswerService answerService, IQuestionService questionService, IAnswerOptionService answerOptionService)
        {
            _responseService = responseService;
            _answerService = answerService;
            _questionService = questionService;
            _answerOptionService = answerOptionService;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> Display(int surveyId)
        {
            var responses = await _responseService.GetAllAsync();
            var surveyResponses = responses.Where(r => r.Survey.Id == surveyId);
            var result = surveyResponses.SelectMany(r => r.Answers).ToList();
            return View(result);
        }
    }
}

src/WebUI/SurveyApp.Mvc/Controllers/QuestionsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using SurveyApp.Mvc.Models;
using SurveyApp.Services.Services;

namespace SurveyApp.Mvc.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly ISurveyService _surveyService;
        private readonly IQuestionTypeService _questionTypeService;
        private readonly IQuestionService _questionService;
        private readonly IQuestionOptionService _questionOptionService;
        private readonly IMemoryCache _memoryCache;
        public QuestionsController(ISurveyService surveyService, IQuestionTypeService questionTypeService, IQuestionService questionService, IQuestionOptionService questionOptionService, IMemoryCache memoryCache)
        {
            _surveyService = surveyService;
            _questionTypeService = questionTypeService;
            _questionService = questionService;
            _questionOptionService = questionOptionService;
            _memoryCache = memoryCache;
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.Surveys = await getSurveysForSelectListAsync();
            ViewBag.QuestionTypeRequest = await getQuestionTypeForSelectListAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(QuestionRequestModel request)
        {
            if (ModelState.IsValid)
            {
                var questionId = await _questionService.CreateAndReturnIdAsync(request.QuestionRequest);
                request.QuestionOptionRequest.QuestionId = questionId;

                await _questionOptionService.CreateAsync(request.QuestionOptionRequest);
                return RedirectToAction("Index", "Home");
            }
            return NotFound();
        }

        private async Task<IEnumerable<SelectListItem>> getQuestionTypeForSelectListAsync()
        {
            var surveyList = await _questionTypeService.GetAllAsync();
            var selectListItems = surveyList.Select(questionType => new SelectListItem
            {
                Value = questionType.Id.ToString(),
                Text = questionType.Type
            });
            return selectListItems;
        }

        private async Task<IEnumerable<SelectListItem>> getSurveysForSelectListAsync()
        {
            var surveyList = await _surveyService.GetAllAsync();
            var selectListItems = surveyList.Select(survey => new SelectListItem
            {
                Value = survey.Id.ToString(),
                Text = survey.Name
            });
            return selectListItems;
        }
    }
}

src/WebUI/SurveyApp.Mvc/Controllers/SurveysController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Azure.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using SurveyApp.DataTransferObjects.Requests;
using SurveyApp.DataTransferObjects.Responses;
using SurveyApp.Mvc.CacheTools;
using SurveyApp.Mvc.Models;
using SurveyApp.Services.Services;
using System.Diagnostics;

namespace SurveyApp.Mvc.Controllers
{
    public class SurveysController : Controller
    {
        private readonly ILogger<SurveysController> _logger;
        private readonly ISurveyService _surveyService;
        private readonly ISurveyTypeService _surveyTypeService;
        private readonly IResponseService _responseService;
        private readonly IAnswerService _answerService;
        private readonly IAnswerOptionService _answerOptionService;
        private readonly ISurveyStatusService _surveyStatusService;
        private readonly IMemoryCache _memoryCache;
        private readonly INotyfService _notyf;
        public SurveysController(ILogger<SurveysController> logger, ISurveyService surveyService, IAnswerService answerService, IAnswerOptionService answerOptionService, IResponseService responseService, ISurveyStatusService surveyStatusService, ISurveyTypeService surveyTypeService, IMemoryCache memoryCache, INotyfService notyf)
        {
            _logger = logger;
            _surveyService = surveyService;
            _answerService = answerService;
            _answerOptionService = answerOptionService;
            _responseService = responseService;
            _surveyStatusService = surveyStatusService;
            _surveyTypeService = surveyTypeService;
            _memoryCache = memoryCache;
            _notyf = notyf;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> Display(int surveyId)
        {
            var survey = await _surveyService.GetByIdAsync(surveyId);
            return View(survey);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            ViewBag.SurveyStatus = await getSurveyStatusForSelectListAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SurveyRequest request)
        {
            if (ModelState.IsValid)
            {
                await _surveyService.CreateAsync(request);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.SurveyStatus = _surveyStatusService.GetAllAsync();
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.SurveyStatus = await getSurveyStatusForSelectListAsync();
            ViewBag.Surveys = await getSurveysForSelectListAsync();

            var survey = await _surveyService.GetByIdAsync(id);

            return View(survey);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, SurveyRequest request)
        {
            if (await _surveyService.SurveyIsExists(id))
            {
                if (ModelState.IsValid)
                {
                    await _surveyService.UpdateAsync(request);
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.SurveyStatus = getSurveyStatusForSelectListAsync();
                return View();
            }
            return NotFound();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete()
        {
            ViewBag.Surveys = await getSurveysForSelectListAsync();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (await _surveyService.SurveyIsExists(id))
            {
                if (ModelState.IsValid)
                {
                    await _surveyService.DeleteAsync(id);
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> SubmitAnswers(ResponseViewModel response)
        {

            try
            {
                var responseRequest = new SurveyResponseRequest
                {
                    RespondentId = 1,
                    SurveyId = response.SurveyId,
                };

                var responseId = await _responseService.CreateAndReturnIdAsync(responseRequest);

                foreach (var answer in response.Answers)
                {
                    var answerRequest = new AnswerRequest
                    {
                        AnswerText = answer.AnswerText,
                        QuestionId = answer.QuestionId,
                        ResponseId = responseId,
                    };

                    var answerId = await _answerService.CreateAndReturnIdAsync(answerRequest);

                    if (answer.AnswerOptionIds != null)
                    {
                        foreach (var answerOptionId in answer.AnswerOptionIds)
                        {
                            var answerOptionRequest = new AnswerOptionRequest
                            {
                                AnswerId = answerId,
                                QuestionOptionId = answerOptionId,
                            };
                            await _answerOptionService.CreateAsync(answerOptionRequest);
                        }
                    }

                    if (answer.AnswerOptionId != null)
                    {
                        var answerOptionRequest = new AnswerOptionRequest
                        {
                            AnswerId = answerId,
                            QuestionOptionId = answer.AnswerOptionId,
                        };
                        await _answerOptionService.CreateAsync(answerOptionRequest);
                    }

                }
                var successMessage = "Sending successful!";
                _notyf.Success(successMessage);
            }
            catch (Exception)
            {
                var errorMessage = "An error occurred, please try again.";
                _notyf.Error(errorMessage);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> GetSurveysByTypeId(int surveyTypeId)
        {
            var surveys = await _surveyService.GetSurveysByTypeIdAsync(surveyTypeId);
            return ViewComponent("SurveyList", surveys);
        }

        private async Task<IEnumerable<SelectListItem>> getSurveysForSelectListAsync()
        {
            var surveyList = await _surveyService.GetAllAsync();
            var selectListItems = surveyList.Select(survey => new SelectListItem
            {
                Value = survey.Id.ToString(),
                Text = survey.Name
            });
            return selectListItems;
        }

        private async Task<IEnumerable<SelectListItem>> getSurveyStatusForSelectListAsync()
        {
            var surveyStatusList = await _surveyStatusService.GetAllAsync();
            var selectListItems = surveyStatusList.Select(status => new SelectListItem
            {
                Value = status.Id.ToString(),
                Text = status.Status
            });
            return selectListItems;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/WebUI/SurveyApp.Mvc/Views/Shared/_ChartDisplay.cshtml
@model SurveyDisplayResponse

<a class="zoom-anim text-reset text-decoration-none" asp-route-surveyId="@Model.Id" asp-action="Display" asp-controller="Answers">
    <div class="card">
        <img src="@Model.ImageUrl" class="img-fluid" />
        <div class="card-body">
            <h4 class="card-title">@Model.Name</h4>
            <p class="card-text"> @Model.Description</p>
            <p class="card-text"> @Model.EndDate</p>
        </div>
    </div>
</a>

src/WebUI/SurveyApp.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - SurveyApp.Mvc</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/SurveyApp.Mvc.styles.css" asp-append-version="true" />
    </head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase mb-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Survey App</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded" asp-area="" asp-controller="Surveys" asp-action="Index">Surveys</a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded" asp-area="" asp-controller="Answers" asp-action="Index">Chart</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item mx-0 mx-lg-1">
                                <div class="dropdown">
                                    <a class="nav-link py-3 px-0 px-lg-3 rounded dropdown-toggle" href="" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
                                        Admin
                                    </a>
                                    <div class="dropdown-menu bg-secondary" aria-labelledby="dropdownMenuButton">
                                        <a class="nav-link py-3 px-0 px-lg-3 rounded" asp-area="" asp-controller="Surveys" asp-action="Create">Create Survey</a>
                                        <a class="nav-link py-3 px-0 px-lg-3 rounded" asp-area="" asp-controller="Surveys" asp-action="Edit">Edit Survey</a>
                                        <a class="nav-link py-3 px-0 px-lg-3 rounded" asp-area="" asp-controller="Surveys" asp-action="Delete">Delete Survey</a>
                                        <a class="nav-link py-3 px-0 px-lg-3 rounded" asp-area="" asp-controller="Questions" asp-action="Create">Create Question</a>
                                    </div>
                                </div>
                            </li>
                        }
                        <li class="nav-item mx-0 mx-lg-1">
                            <partial name="_LoginPartial" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

    <footer class="footer position-relative text-center">
        <div class="container">
            &copy; 2023 - SurveyApp.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>    
</html>

src/WebUI/SurveyApp.Mvc/Views/Shared/_SurveyPartial.cshtml
@model SurveyDisplayResponse

<a class="zoom-anim text-reset text-decoration-none" asp-route-surveyId="@Model.Id" asp-action="Display" asp-controller="Surveys">
    <div class="card">
        <img src="@Model.ImageUrl" class="img-fluid" />
        <div class="card-body">
            <h4 class="card-title">@Model.Name</h4>
            <p class="card-text"> @Model.Description</p>
            <p class="card-text"> @Model.EndDate</p>
        </div>
    </div>
</a>